version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ${db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      user: ${user}
      password: ${password}
      host: db  # This refers to the "db" service name
      port: 5432
      db: ${db}
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Exposing your app on port 8000
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
